# name: Deploy on Push

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-22.04

#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v3

#       - name: SSH and Deploy
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.SERVER_HOST }}
#           username: ${{ secrets.SERVER_USER }}
#           key: ${{ secrets.SERVER_SSH_KEY }}
#           script: |
#             export NVM_DIR="$HOME/.nvm"
#             [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
#             nvm use 22.15.0
#             cd /home/tenderlandprod/tenderland-bot
#             git pull
#             npm install
#             npm run build
#             pm2 restart all

name: Deploy on Dev Push

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.10

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_DIGITAL_OCEAN_HOST }}
          username: ${{ secrets.SERVER_DIGITAL_OCEAN_USER }}
          password: ${{ secrets.SERVER_DIGITAL_OCEAN_PASSWORD }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 22.15.0
            cd /root/tenderland-bot
            git pull
            npm install
            npm run build
            pm2 restart all

            name: Deploy on Dev Push
