name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    name: Deploy to Dev Environment

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: SSH and Deploy to Dev
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_DIGITAL_OCEAN_HOST }}
          username: ${{ secrets.SERVER_DIGITAL_OCEAN_USER }}
          password: ${{ secrets.SERVER_DIGITAL_OCEAN_PASSWORD }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 22.15.0
            cd /root/tenderland-bot
            git pull
            npm install
            npm run build
            pm2 restart all

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Deploy to Production Environment

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: SSH and Deploy to Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm use 22.15.0
            cd /home/tenderland-bot
            git pull
            npm install
            npm run build
            pm2 restart all
